### ISSUE TITLE
Foundation of Project Concord

### ISSUE THREAD

**Issue by nadnbuds** [dzhan008/Concord#1]
This should have all the necessary classes that will allow development to start at its barest form. These include:

- Game Manager
- Resource Manager
- Any other helpful base classes (like Object Poolers)

The game should work around the managers as they will promote the structure of the game

**Comment by dzhan008** [comment]
So I figured that it would be hard to create managers without having anything in the game yet, so I'm tabling this for now until we actually need it. Basic empty classes were made. Also leaving a reference to blackboard pattern here:

http://aigamedev.com/open/article/static-blackboard/
